/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-2:1807d75f-cd54-40cf-8732-e509c45486a3",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_eNCH7oKvb",
    "aws_user_pools_web_client_id": "2mfpc11n1unmedg0580od41bfh",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://kp7674b4tzbwjdh5inx3d4j4gi.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
